### ISSUE TITLE
Demo is not working?

### ISSUE THREAD

**Issue by ohmegah** [ImaginaryVillain/community_lights#13]
Your project seems very interesting, I tried checking it out in MZ but the demo appears to be completely broken and does not launch at all

**Comment by AdriLez** [comment]
The zip file only contains the data and js folder of a regular rpgmz project. So it has no image or music.
If you can't launch the demo at all, my best bet would be that you are trying to use the project directly from the zip.
To make it work properly, you have to paste the content of the zip in a clean rpgmz project.

I just tried now with the last version of the script and I had no problem.

**Comment by ohmegah** [comment]
Ok I see what you mean, usually demos are packaged with all the used files to avoid this, you might want to consider this. I tried out some of the functionalities and editing the js file I am unable to get the "night" box to grow to resolution size of my game and I end up with this 
![image](https://user-images.githubusercontent.com/60045747/104664973-d4e69680-56d0-11eb-878f-ebd5fa992107.png)

Are you guys on discord? I'd love to get in touch on this.

**Comment by AdriLez** [comment]
Did updated the screensize X and Y parameters of the plugin? If it is the case, I would suggest to continue the conversation on rpgmakerweb's related topic: https://forums.rpgmakerweb.com/index.php?threads/community-lighting-mv-mz.124274/page-25
