### ISSUE TITLE
Lights Disappear from events after battle ends

### ISSUE THREAD

**Issue by aerd2** [ImaginaryVillain/community_lights#22]
I don't know if it's intentional, but events with id stop glowing after the battle ends.

**Comment by AdriLez** [comment]
If you made reference to the monsters on the overworld map of the demo, it is intentional: their 'kill switch' are activated when defeating them, so those event no longer produce any light.

If it is not what you were referring to, can you explain me a simple way to reproduce this strange behavior?
I wasn't able to replicate it myself.

**Comment by aerd2** [comment]
Okay so I set up an event with this: <cl: fire 50 #51fffb B25 1>, then activated it upon entry with a plugin command. And I noticed that light stop when I open and close menu window.

**Comment by AdriLez** [comment]
I created the simplest map possible attempting to replicate the issue, but I hadn't much result:

![Capture](https://user-images.githubusercontent.com/70440862/110125700-e80a0e80-7dc3-11eb-9cdb-1be5e4f39150.PNG)
![Capture1](https://user-images.githubusercontent.com/70440862/110125704-e8a2a500-7dc3-11eb-968e-8e08b76435e8.PNG)
![Capture2](https://user-images.githubusercontent.com/70440862/110125705-e93b3b80-7dc3-11eb-961f-47fbe17212d4.PNG)


https://user-images.githubusercontent.com/70440862/110124615-96ad4f80-7dc2-11eb-862e-3c516a47ebfe.mp4

**Comment by aerd2** [comment]
![image](https://user-images.githubusercontent.com/1911661/110137009-446f2d00-7dc8-11eb-8768-780b7d6d544d.png)
<Hide Shadow><cl: fire 50 #51fffb B0 1>
![image](https://user-images.githubusercontent.com/1911661/110137097-5f41a180-7dc8-11eb-878b-054dab7a68b1.png)
![image](https://user-images.githubusercontent.com/1911661/110137230-84361480-7dc8-11eb-872d-e81896fc27d8.png)

https://user-images.githubusercontent.com/1911661/110138471-efccb180-7dc9-11eb-8780-a9ec02d0505c.mp4

**Comment by AdriLez** [comment]
Ok, It seems to be linked to the 'Reset Light' parameter that wasn't activated in my example.
Thanks for your report, I will look at it.

**Comment by AdriLez** [comment]
Version 3.9 of the script should do it.
