### ISSUE TITLE
Incompatible with Visustella Action Sequence Camera

### ISSUE THREAD

**Issue by Ner-In** [ImaginaryVillain/community_lights#24]
Just as the title says. Running these two plugins makes the tint start (or be visible) from the centre of the screen.

Here's a picture of what happens.
![obraz](https://user-images.githubusercontent.com/1911661/113224859-3e178800-9284-11eb-9958-ca89218ea166.png)

**Comment by AdriLez** [comment]
First, are you sure the problem only occur when VASC and this plugin is active and that no other plugins may be in conflict?
Second, did you tried playing with the 'screensize' option of Community Lighting to match your screensize?

**Comment by aerd2** [comment]
First: I'm 95% sure it's because of VASC and 100% it's because some Vistustella incompatibility, because I only had Visustella plugins and lighting enabled and after removing VASC it fixed itself.
Second: Yes.

**Comment by AdriLez** [comment]
Does changing the plugin position below or above the Visustella plugin suit have any impact?
I will try later today to replicate the issue myself with the MV version of VASC, as I don't have the MZ version and even if I had,
it wouldn't be possible to read through its code.
