### ISSUE TITLE
CommunityLightingMZDemo missing audio/me/Inn.ogg

### ISSUE THREAD

**Issue by Andross-1** [ImaginaryVillain/community_lights#25]
When asking the Dark cultist NPC for recovery in the MZ Demo project (I have not checked the MV one), it attempts to play Inn.ogg, which it is not present, spitting out an error:

> Failed to load
> audio/me/Inn.ogg

Very minor clearly, but I thought I should report it.

**Comment by AdriLez** [comment]
Yes, it should have been Inn1.ogg since they added another variation in MZ.
Thanks for the catch, I will post a correction very soon.

**Comment by AdriLez** [comment]
It was fixed some months ago, this issue can be closed.
