### ISSUE TITLE
Cleaner code and modifications

### ISSUE THREAD

**Issue by NerdyChara** [ImaginaryVillain/community_lights#36]
I was wondering if it would be possible to replace the match with Regex.test which is supposed to be faster? And on my last pull request I forgot to take into account multiple spaces separating arguments. May I fix it? In addition would you be allowing a default brightness map notetag for lights? This value can be set back to zero every time the player goes to a different map.

**Comment by AdriLez** [comment]
Regex.test is better for simple boolean check (what we does), so it does feel as a possible improvement.
Always add fixes if you found any error, you are probably the best placed to find them.
Your notetag can have its use, as long as it is documented and that the default behavior remains the same, it is a nice addition

**Comment by NerdyChara** [comment]
I will remember to add documentation for the the default brightness notetag. I was debating whether or not to use it for the background tint or for the lights themselves; I ultimately decided on using it to control the light brightness.
