### ISSUE TITLE
Plugin Command: RegionLights with a cycle option

### ISSUE THREAD

**Issue by NerdyChara** [ImaginaryVillain/community_lights#40]
I don't fully know how the code works for the light tags, but I would like to see a way to see a way to set cycling lights for a region defined similarly to the tag for the events. If it was explained a little further; I could implement it myself.

**Comment by AdriLez** [comment]
Cycling lights are related to events. See Game_Event.prototype.incrementLightCycle and Game_Event.prototype.initLightData for more info.

**Comment by NerdyChara** [comment]
I see. Unfortunately there is no container for the cycling lights if I were to try to changing lights for a region light. Thank you for answering my inquiry.
