### ISSUE TITLE
Light mask keeps getting offset

### ISSUE THREAD

**Issue by NerdyChara** [ImaginaryVillain/community_lights#57]
After my player character walks for a little while; the light ball moves out of place. Then snaps back 

![image](https://user-images.githubusercontent.com/63977781/149583521-0eae34b6-642a-4aa8-bbc2-68da147d645a.png)

**Comment by AdriLez** [comment]
Is it by any chance a map with a scrolling on the X-axis?
Also, can you explain in deeper detail how it is offset (for example, show a picture of how it should be?).
Right now, I don't have the feeling anything is out of place?

**Comment by NerdyChara** [comment]
It does scroll horizontally actually. And this is how it is supposed to look. 
![image](https://user-images.githubusercontent.com/63977781/149677303-92369306-0027-4428-85a8-7b8a01b64f6a.png)

**Comment by AdriLez** [comment]
I guess there may be a bug with scrolling maps.
However I still don't get what is the problem with the first picture, it seems as it should be.
