### ISSUE TITLE
Feature Request: Light comment on any line

### ISSUE THREAD

**Issue by NerdyChara** [ImaginaryVillain/community_lights#58]
I would like to be able to the comment on the event's page wherever I want instead of only the first line; however with the way the current code architecture, it is unfortunately a little difficult to accomplish.

**Comment by AdriLez** [comment]
Seems totally unnecessary, why would you want to do that in the first place?
If you have another plugin who also look at the first comment, you can put both notetag in the same comment, no?

**Comment by NerdyChara** [comment]
So wait I could hypothetically put "<cl: light 122 #FFFFFF>" and "<projY:20>" in the same comment? :O

**Comment by NerdyChara** [comment]
In regards to plugins that take comments and I typically put the comment up top of the page: I'm using this plugin and Galv map projectiles and Mog_PickupThrow

**Comment by AdriLez** [comment]
If you are using the Note Tag Key plugin parameter, you will have no problem with Galv projectiles (who can use any comment in a page, even one with <cl: light 122 #FFFFFF> in it).
Mog_PickupThrow requires it to be the first command, but you can have both in the same comment (just make sure Mog's notetag is placed first).

How to have all at the same time:

◆Commet：throw : X
：           ：projY:20
：           ：<CL: Fire 100 #663300 B15>

OR

◆Commentaire：throw : X
：           ：<CL: Fire 100 #663300 B15>
◆Commentaire：projY:20

**Comment by AdriLez** [comment]
Theorically, it is possible to check every comment in the page, but it would be a bunch of computation at each map load and page change for a benefit who doesn't seem worth, as there is already kill switches and the event notetag as alternative.

**Comment by NerdyChara** [comment]
Thank you. I can now close this issue.
