### ISSUE TITLE
Feature request/Bug Day Night Cycle

### ISSUE THREAD

**Issue by NerdyChara** [ImaginaryVillain/community_lights#59]
I would like to the ability to completely turn off the day/night cycle. It was my initial assumption that if there was no day night switch or variables the system was completely off. However with a default timer of 10 ; the game will get progressively dark as the player plays.

**Comment by AdriLez** [comment]
You don't want to use the day/night system at all -> Don't put any DayNight tag in your map note
You want to not have any light at all in a day/night map -> Use the plugin command to turn the plugin off on that map
You want the time to freeze the time at the current hour -> Put 'DayNight 0' in your mapnote to says the plugin the time don't flow on this map. Alternatively, you can freeze the time with a 'Daynight speed 0' plugin command.

**Comment by NerdyChara** [comment]
The day night speed initializes itself to 10. I was actually really startled by the fact during testing someone else's playthrough the level was completely pitch black. I'd like the ability to opt before the game even starts without having to do anything else but configure the plugin.

**Comment by AdriLez** [comment]
My first idea would be to put an auto or a parallel event in your starting location with the plugin command 'Daynight speed 0'.
It will do the trick. You will be probably wanting to have one of such event to initialize a bunch of settings anyway.

But I can see it being very cumbersome to test the other maps, so as I proposed in the MR,
I think a 'initial day speed' parameter is the idea.

**Comment by AdriLez** [comment]
https://github.com/ImaginaryVillain/community_lights/pull/61

**Comment by NerdyChara** [comment]
Yeah that would be pretty good. Thank you

**Comment by NerdyChara** [comment]
Also you can't put "Daynight Speed 0" ;the way the code is arranged it sets the speed to 5000. In the $$.Daynight function it is a less than or equal to zero; not a less then.
