### ISSUE TITLE
Player Radius doesn't work anymore :(

### ISSUE THREAD

**Issue by DarkSearinox92** [ImaginaryVillain/community_lights#64]
Hello guys,

i updated the script with the last 4.4 and the Player Radius doesn't work anymore.

With the 4.2, all it works perfectly :(

**Comment by AdriLez** [comment]
As said on the forum, you may post somewhere a vanilla project who highlight the bug.

**Comment by DarkSearinox92** [comment]
I found the problem. If you set the raidus <100, the radius stop to work.

**Comment by AdriLez** [comment]
Should be fixed with https://github.com/ImaginaryVillain/community_lights/pull/66
